version: '3.5'

services:

  web:
    image: projectsidewalk/web
    container_name: projectsidewalk-web
    build:
      context: ./
    depends_on:
      - db
    volumes:
      - "./:/opt"
      - "/opt/node_modules"
    ports:
      - "9000:9000"
    environment:
      # Tell our application how to connect to the db
      - DATABASE_URL=jdbc:postgresql://db:5432/sidewalk
      - DATABASE_USER=sidewalk
      - DATABASE_PASSWORD=sidewalk

  db:
    image: projectsidewalk/db
    container_name: projectsidewalk-db
    build:
      context: ./db/
    volumes:
      - "./db/init.sh:/docker-entrypoint-initdb.d/init.sh"
      - "./db:/opt"
    ports:
      - "5432:5432"
    environment:
      # Default user/password; tell postgres to default to these users.
      # If we don't give it at least one password, it will refuse to start.
      - POSTGRESS_USER=sidewalk
      - POSTGRES_PASSWORD=sidewalk
